add korea
disease-sh/API pull request #890
Opened 2020-10-02 22:40 UTC by phamleduy04

I added Korea but idk why I when I tried to get `/v3/covid-19/gov` the array returns empty string. 
<img width="352" alt="Screen Shot 2020-10-02 at 5 39 48 PM" src="https://user-images.githubusercontent.com/32657584/94975130-4578f700-04d6-11eb-9bef-3e2cfa308fd1.png">
 I tried to get `/v3/covid-19/gov/%20/ and it returns the request.

2020-10-03 13:41 UTC, ebwinters commented
What is this line returning for Korea? My guess is Korea is not a country - it is either South or North
`const standardizedCountryName = nameUtils.getCountryData(country.trim()).country;`

2020-10-03 13:46 UTC, phamleduy04 commented
Its South Korea

2020-10-03 23:08 UTC, ebwinters commented
Tests still failing m8 once they pass I'll give it a review

2020-10-05 04:12 UTC, phamleduy04 commented
<img width="1042" alt="Screen Shot 2020-10-04 at 11 10 52 PM" src="https://user-images.githubusercontent.com/32657584/95039651-ffb75c80-0696-11eb-9b69-7cf5553247a8.png">
<img width="1045" alt="Screen Shot 2020-10-04 at 11 11 31 PM" src="https://user-images.githubusercontent.com/32657584/95039655-01812000-0697-11eb-8775-26c3b6d3056d.png">

Mine v2 and v3 are ok, something else breaking the test! @ebwinters

2020-10-05 12:54 UTC, ebwinters requested changes

2020-10-05 12:54 UTC, ebwinters commented on scrapers/covid-19/govScrapers/getGovData.js
> +const sKoreaData = require('./getSKorea');
southKoreaData

2020-10-05 12:54 UTC, ebwinters commented on scrapers/covid-19/govScrapers/getSKorea.js
> +const axios = require('axios');
Call this file getSouthKorea

2020-10-05 12:54 UTC, ebwinters commented on scrapers/covid-19/govScrapers/getSKorea.js
> +		logger.err('Error: Requesting Korea Gov Data failed!', err);
South

2020-10-06 12:20 UTC, ebwinters approved these changes

2020-10-06 12:21 UTC, merged